id: P010367
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:46:13.768751
source_metadata:
  id: bdr:W1KG4284
  title: ཤངས་པ་བཀའ་བརྒྱུད་སོགས་པའི་སྣ་ཚོགས་གླེགས་བམ
  author: ''
  volumes:
    a68babe311cf48b8a401bf5f323f6cda:
      image_group_id: I1PD100486
      title: ''
      volume_number: 1
      total_pages: 688
      base_file: v001.txt
    0159fe20b6564fa194e68cc3c05cbef5:
      image_group_id: I1PD100487
      title: ''
      volume_number: 2
      total_pages: 706
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
