id: I0F9D554E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:17:26+00:00'
last_modified: '2022-06-08T13:04:32.041069+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4284
  title: ཤངས་པ་བཀའ་བརྒྱུད་སོགས་པའི་སྣ་ཚོགས་གླེགས་བམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1A5A:
      image_group_id: I1PD100486
      title: ''
      total_pages: 688
      order: 1
      base_file: 1A5A.txt
    '7980':
      image_group_id: I1PD100487
      title: ''
      total_pages: 706
      order: 2
      base_file: 7980.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
