id: I0F9D554E
legacy_id: P010367
ocr_import_info:
  bdrc_scan_id: W1KG4284
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T12:13:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:31:12.746765+00:00'
last_modified: 2022-08-31 23:31:51.340491
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4284
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4284
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤངས་པ་བཀའ་བརྒྱུད་སོགས་པའི་སྣ་ཚོགས་གླེགས་བམ།
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.8805999989012597
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD100486:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100486
      total_pages: 688
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD100486.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8609510035431543
    legacy_id: v001
  I1PD100487:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100487
      total_pages: 706
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD100487.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9014685604413796
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
